use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fs;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};

/// Library error surface for `agent-memory`. The forge-domain pattern:
/// callers can pattern-match the named variants when they want to recover
/// (e.g. retry on a transient IO failure, surface a useful "edit a different
/// file" message on a generated-file write attempt); everything else flows
/// through `Other(anyhow::Error)` so internal `?` keeps working.
#[derive(Debug, thiserror::Error)]
pub enum MemoryError {
    /// Caller tried to write to a generated path (memory/l1_insight.md or
    /// memory/index.json). These are rebuilt from L2/L3 — see SOP.
    #[error("write to generated memory path is forbidden: {path}")]
    GeneratedPathWrite { path: PathBuf },

    /// Validation of durable memory text rejected the content (e.g. detected
    /// secret-like material, unverified speculation). Body contains the
    /// individual violation messages.
    #[error("durable memory validation failed:\n  - {}", .violations.join("\n  - "))]
    Validation { violations: Vec<String> },

    /// Escape hatch — internal anyhow::Error from IO / serde paths.
    #[error(transparent)]
    Other(#[from] anyhow::Error),
}

pub type MemoryResult<T> = std::result::Result<T, MemoryError>;

pub const DEFAULT_META_RULES: &str = r#"# Meta Rules

- Keep the active context small: load L0 meta rules and L1 index by default, fetch deeper memory on demand.
- Only write memory from verified tool results.
- Do not store secrets, raw credentials, guesses, temporary variables, or one-off command output.
- Use `update_working_checkpoint` for short-term facts needed during the current run.
- Use `start_long_term_update` before writing durable L2 facts or updating L3 skills.
- Prefer updating an existing skill over creating a duplicate when the workflow is the same.
"#;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MemoryLayer {
    L0MetaRules,
    L2GlobalFacts,
    L3Skill,
    L4SessionArchive,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MemoryIndexEntry {
    pub id: String,
    pub layer: MemoryLayer,
    pub title: String,
    pub keywords: Vec<String>,
    pub path: PathBuf,
    pub summary: String,
    pub updated_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct MemoryIndex {
    pub entries: Vec<MemoryIndexEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryDocument {
    pub entry: MemoryIndexEntry,
    pub body: String,
}

#[derive(Debug, Clone, Default)]
pub struct MemoryPaths {
    pub memory_dir: PathBuf,
    pub skills_dir: PathBuf,
    pub sessions_dir: PathBuf,
}

impl MemoryPaths {
    pub fn new(
        memory_dir: impl Into<PathBuf>,
        skills_dir: impl Into<PathBuf>,
        sessions_dir: impl Into<PathBuf>,
    ) -> Self {
        Self {
            memory_dir: memory_dir.into(),
            skills_dir: skills_dir.into(),
            sessions_dir: sessions_dir.into(),
        }
    }

    pub fn index_path(&self) -> PathBuf {
        self.memory_dir.join("index.json")
    }

    pub fn l1_insight_path(&self) -> PathBuf {
        self.memory_dir.join("l1_insight.md")
    }

    pub fn meta_rules_path(&self) -> PathBuf {
        self.memory_dir.join("meta_rules.md")
    }
}

pub fn ensure_memory_layout(paths: &MemoryPaths) -> MemoryResult<()> {
    fs::create_dir_all(&paths.memory_dir)
        .with_context(|| format!("create {}", paths.memory_dir.display()))?;
    fs::create_dir_all(&paths.skills_dir)
        .with_context(|| format!("create {}", paths.skills_dir.display()))?;
    fs::create_dir_all(&paths.sessions_dir)
        .with_context(|| format!("create {}", paths.sessions_dir.display()))?;

    write_if_missing(&paths.meta_rules_path(), DEFAULT_META_RULES)?;
    write_if_missing(
        &paths.memory_dir.join("global_facts.md"),
        "# Global Facts\n\nStable, verified facts can be added here by `start_long_term_update` flows.\n\nDo not store guesses, secrets, or one-off command output.\n",
    )?;
    write_if_missing(
        &paths.l1_insight_path(),
        "# L1 Insight\n\nGenerated by `agent-memory`; rebuild the index after L2/L3 changes.\n",
    )?;
    write_if_missing(&paths.memory_dir.join("session_archive.jsonl"), "")?;
    Ok(())
}

pub fn rebuild_index(paths: &MemoryPaths) -> MemoryResult<MemoryIndex> {
    ensure_memory_layout(paths)?;
    let mut entries = Vec::new();
    collect_memory_file(
        &mut entries,
        MemoryLayer::L0MetaRules,
        "meta-rules",
        "Meta Rules",
        paths.meta_rules_path(),
    )?;
    collect_memory_file(
        &mut entries,
        MemoryLayer::L0MetaRules,
        "memory-management-sop",
        "Memory Management SOP",
        paths.memory_dir.join("memory_management_sop.md"),
    )?;
    collect_memory_file(
        &mut entries,
        MemoryLayer::L2GlobalFacts,
        "global-facts",
        "Global Facts",
        paths.memory_dir.join("global_facts.md"),
    )?;
    collect_skills(&mut entries, paths)?;
    collect_session_archive(&mut entries, paths)?;

    entries.sort_by(|a, b| {
        a.layer_label()
            .cmp(b.layer_label())
            .then_with(|| a.id.cmp(&b.id))
    });
    let index = MemoryIndex { entries };
    write_index(paths, &index)?;
    write_l1_insight(paths, &index)?;
    Ok(index)
}

pub fn load_or_rebuild_index(paths: &MemoryPaths) -> MemoryResult<MemoryIndex> {
    ensure_memory_layout(paths)?;
    let path = paths.index_path();
    if !path.is_file() {
        return rebuild_index(paths);
    }
    let text = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    serde_json::from_str(&text)
        .with_context(|| format!("parse {}", path.display()))
        .or_else(|_| rebuild_index(paths))
}

pub fn write_index(paths: &MemoryPaths, index: &MemoryIndex) -> MemoryResult<()> {
    fs::write(
        paths.index_path(),
        serde_json::to_string_pretty(index).context("serialize memory index")?,
    )
    .with_context(|| format!("write {}", paths.index_path().display()))?;
    Ok(())
}

pub fn write_l1_insight(paths: &MemoryPaths, index: &MemoryIndex) -> MemoryResult<()> {
    fs::write(paths.l1_insight_path(), render_l1_insight(index, 18))
        .with_context(|| format!("write {}", paths.l1_insight_path().display()))?;
    Ok(())
}

pub fn durable_memory_violations(text: &str) -> Vec<String> {
    let mut violations = Vec::new();
    if let Some(line) = find_secret_like_line(text) {
        violations.push(format!("possible secret material on line {line}"));
    }
    if let Some((line, term)) = find_uncertain_line(text) {
        violations.push(format!(
            "unverified wording `{term}` on line {line}; durable memory must be action-verified"
        ));
    }
    violations
}

pub fn validate_durable_memory_text(text: &str) -> MemoryResult<()> {
    let violations = durable_memory_violations(text);
    if violations.is_empty() {
        Ok(())
    } else {
        Err(MemoryError::Validation { violations })
    }
}

pub fn search_index(index: &MemoryIndex, query: &str, limit: usize) -> Vec<MemoryIndexEntry> {
    let query_terms = terms(query);
    let limit = limit.clamp(1, 50);
    let mut scored = index
        .entries
        .iter()
        .filter_map(|entry| {
            let haystack = format!(
                "{} {} {} {}",
                entry.id,
                entry.title,
                entry.summary,
                entry.keywords.join(" ")
            )
            .to_lowercase();
            let score = if query_terms.is_empty() {
                1
            } else {
                query_terms
                    .iter()
                    .filter(|term| haystack.contains(term.as_str()))
                    .count()
            };
            (score > 0).then_some((score, entry.clone()))
        })
        .collect::<Vec<_>>();
    scored.sort_by(|(a_score, a), (b_score, b)| {
        b_score
            .cmp(a_score)
            .then_with(|| a.layer_label().cmp(b.layer_label()))
            .then_with(|| a.id.cmp(&b.id))
    });
    scored
        .into_iter()
        .take(limit)
        .map(|(_, entry)| entry)
        .collect()
}

pub fn fetch_memory(
    paths: &MemoryPaths,
    id_or_path: &str,
    max_bytes: usize,
) -> Result<MemoryDocument> {
    let index = load_or_rebuild_index(paths)?;
    let entry = index
        .entries
        .iter()
        .find(|entry| {
            entry.id == id_or_path
                || entry.path == Path::new(id_or_path)
                || entry.path.to_string_lossy() == id_or_path
        })
        .cloned()
        .with_context(|| format!("memory entry not found: {id_or_path}"))?;
    let mut body = fs::read_to_string(&entry.path)
        .with_context(|| format!("read {}", entry.path.display()))?;
    if body.len() > max_bytes {
        truncate_utf8(&mut body, max_bytes);
        body.push_str("\n...[truncated]...");
    }
    Ok(MemoryDocument { entry, body })
}

pub fn planner_memory_context(paths: &MemoryPaths) -> MemoryResult<String> {
    let index = load_or_rebuild_index(paths)?;
    let meta_rules = fs::read_to_string(paths.meta_rules_path())
        .unwrap_or_else(|_| DEFAULT_META_RULES.to_string());
    let l1_insight = fs::read_to_string(paths.l1_insight_path())
        .unwrap_or_else(|_| render_l1_insight(&index, 18));
    Ok(format!(
        "### [L0 META RULES]\n{}\n\n### [L1 INSIGHT]\n{}\n\n### [L1 MEMORY INDEX]\n{}",
        compact_text(&meta_rules, 2_500),
        compact_text(&l1_insight, 2_500),
        render_l1_index(&index, 40)
    ))
}

pub fn render_l1_insight(index: &MemoryIndex, skill_limit: usize) -> String {
    let l0 = ids_for_layer(index, MemoryLayer::L0MetaRules, usize::MAX);
    let l2 = ids_for_layer(index, MemoryLayer::L2GlobalFacts, usize::MAX);
    let l3 = titles_for_layer(index, MemoryLayer::L3Skill, skill_limit);
    let l4_count = index
        .entries
        .iter()
        .filter(|entry| entry.layer == MemoryLayer::L4SessionArchive)
        .count();
    let extra_skills = index
        .entries
        .iter()
        .filter(|entry| entry.layer == MemoryLayer::L3Skill)
        .count()
        .saturating_sub(l3.len());

    let mut lines = vec![
        "# L1 Insight".to_string(),
        String::new(),
        "Pointer-only navigation. Keep details in L2/L3/L4 and fetch bodies on demand.".to_string(),
        format!(
            "- L0 meta: {}",
            empty_as(l0.join(" | "), "meta-rules | memory-management-sop")
        ),
        format!("- L2 facts: {}", empty_as(l2.join(" | "), "global-facts")),
        format!(
            "- L3 skills: {}{}",
            empty_as(l3.join(" | "), "(none yet)"),
            if extra_skills > 0 {
                format!(" | +{extra_skills} more via memory_search")
            } else {
                String::new()
            }
        ),
        format!(
            "- L4 sessions: {} indexed; use memory_search before memory_fetch for historical traces.",
            l4_count
        ),
        "- Rules: No execution, no memory | no secrets | read target before durable writes | update existing skill before creating duplicates.".to_string(),
    ];

    if lines.len() > 30 {
        lines.truncate(30);
    }
    lines.join("\n")
}

pub fn render_l1_index(index: &MemoryIndex, limit: usize) -> String {
    index
        .entries
        .iter()
        .take(limit)
        .map(|entry| {
            format!(
                "- id={} layer={} title={} path={} summary={}",
                entry.id,
                entry.layer_label(),
                entry.title,
                entry.path.display(),
                compact_text(&entry.summary, 240)
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn ids_for_layer(index: &MemoryIndex, layer: MemoryLayer, limit: usize) -> Vec<String> {
    index
        .entries
        .iter()
        .filter(|entry| entry.layer == layer)
        .take(limit)
        .map(|entry| entry.id.clone())
        .collect()
}

fn titles_for_layer(index: &MemoryIndex, layer: MemoryLayer, limit: usize) -> Vec<String> {
    index
        .entries
        .iter()
        .filter(|entry| entry.layer == layer)
        .take(limit)
        .map(|entry| compact_text(&entry.title, 80))
        .collect()
}

fn empty_as(value: String, fallback: &str) -> String {
    if value.trim().is_empty() {
        fallback.to_string()
    } else {
        value
    }
}

fn find_secret_like_line(text: &str) -> Option<usize> {
    for (idx, line) in text.lines().enumerate() {
        let lower = line.to_ascii_lowercase();
        if lower.contains("begin ") && lower.contains(" private key") {
            return Some(idx + 1);
        }
        let mentions_secret_key = [
            "api_key",
            "apikey",
            "api key",
            "access_token",
            "refresh_token",
            "token",
            "bearer token",
            "password",
            "passwd",
            "secret_key",
            "private_key",
            "private key",
            "密码",
            "令牌",
            "密钥",
        ]
        .iter()
        .any(|keyword| lower.contains(keyword));
        if mentions_secret_key
            && looks_like_assignment_with_value(line)
            && !looks_like_placeholder(&lower)
        {
            return Some(idx + 1);
        }
    }
    None
}

fn find_uncertain_line(text: &str) -> Option<(usize, &'static str)> {
    const TERMS: &[&str] = &[
        "maybe",
        "probably",
        "i think",
        "not verified",
        "unverified",
        "猜测",
        "可能",
        "也许",
        "大概",
        "推测",
        "未验证",
        "未经验证",
    ];
    for (idx, line) in text.lines().enumerate() {
        let lower = line.to_ascii_lowercase();
        for term in TERMS {
            if lower.contains(term) {
                return Some((idx + 1, term));
            }
        }
    }
    None
}

fn looks_like_assignment_with_value(line: &str) -> bool {
    let Some((_, rhs)) = line.split_once('=').or_else(|| line.split_once(':')) else {
        return false;
    };
    let rhs = rhs
        .trim()
        .trim_matches('`')
        .trim_matches('"')
        .trim_matches('\'');
    rhs.len() >= 4 && rhs.chars().any(char::is_alphanumeric)
}

fn looks_like_placeholder(line: &str) -> bool {
    [
        "placeholder",
        "redacted",
        "<",
        "your_",
        "xxx",
        "example",
        "without secrets",
        "never store",
        "do not store",
        "no secrets",
        "无",
        "占位",
        "示例",
    ]
    .iter()
    .any(|term| line.contains(term))
}

impl MemoryIndexEntry {
    pub fn layer_label(&self) -> &'static str {
        match self.layer {
            MemoryLayer::L0MetaRules => "L0",
            MemoryLayer::L2GlobalFacts => "L2",
            MemoryLayer::L3Skill => "L3",
            MemoryLayer::L4SessionArchive => "L4",
        }
    }
}

fn collect_memory_file(
    entries: &mut Vec<MemoryIndexEntry>,
    layer: MemoryLayer,
    id: &str,
    title: &str,
    path: PathBuf,
) -> Result<()> {
    if !path.is_file() {
        return Ok(());
    }
    let body = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    entries.push(MemoryIndexEntry {
        id: id.to_string(),
        layer,
        title: title.to_string(),
        keywords: keywords_from_text(&format!("{title}\n{body}")),
        path: path.clone(),
        summary: first_content_line(&body).unwrap_or_else(|| title.to_string()),
        updated_at: modified_at(&path),
    });
    Ok(())
}

fn collect_skills(entries: &mut Vec<MemoryIndexEntry>, paths: &MemoryPaths) -> Result<()> {
    if !paths.skills_dir.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(&paths.skills_dir)
        .with_context(|| format!("read {}", paths.skills_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        let skill_path = if path.is_dir() {
            path.join("SKILL.md")
        } else if path.extension().is_some_and(|ext| ext == "md") {
            path
        } else {
            continue;
        };
        if !skill_path.is_file() {
            continue;
        }
        let body = fs::read_to_string(&skill_path)
            .with_context(|| format!("read {}", skill_path.display()))?;
        let content = content_without_front_matter(&body);
        let title = heading(&body).unwrap_or_else(|| {
            skill_path
                .parent()
                .and_then(Path::file_name)
                .and_then(|name| name.to_str())
                .unwrap_or("skill")
                .to_string()
        });
        entries.push(MemoryIndexEntry {
            id: format!("skill:{}", slug(&title)),
            layer: MemoryLayer::L3Skill,
            title: title.clone(),
            keywords: keywords_from_text(&format!("{title}\n{content}")),
            path: skill_path.clone(),
            summary: first_content_line(&body).unwrap_or_else(|| "Reusable task skill".to_string()),
            updated_at: modified_at(&skill_path),
        });
    }
    Ok(())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionArchiveRecord {
    pub session_id: String,
    pub session_path: PathBuf,
    pub goal: String,
    pub status: String,
    pub summary: String,
    pub turns: usize,
    pub key_facts: Vec<String>,
    pub related_skills: Vec<String>,
    pub finished_at: DateTime<Utc>,
}

pub fn append_session_archive_record(
    paths: &MemoryPaths,
    record: &SessionArchiveRecord,
) -> Result<()> {
    ensure_memory_layout(paths)?;
    let archive_path = paths.memory_dir.join("session_archive.jsonl");
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&archive_path)
        .with_context(|| format!("open {}", archive_path.display()))?;
    let line = serde_json::to_string(record).context("serialize session archive record")?;
    use std::io::Write;
    writeln!(file, "{line}").context("write session archive line")?;
    Ok(())
}

fn collect_session_archive(entries: &mut Vec<MemoryIndexEntry>, paths: &MemoryPaths) -> Result<()> {
    let archive_path = paths.memory_dir.join("session_archive.jsonl");
    if archive_path.is_file() {
        collect_memory_file(
            entries,
            MemoryLayer::L4SessionArchive,
            "session-archive",
            "Session Archive",
            archive_path,
        )?;
    }
    if !paths.sessions_dir.exists() {
        return Ok(());
    }
    let mut session_files = fs::read_dir(&paths.sessions_dir)
        .with_context(|| format!("read {}", paths.sessions_dir.display()))?
        .filter_map(Result::ok)
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "jsonl"))
        .collect::<Vec<_>>();
    session_files.sort_by_key(|entry| entry.metadata().and_then(|m| m.modified()).ok());
    for entry in session_files.into_iter().rev().take(20) {
        let path = entry.path();
        let Some(summary) = session_summary(&path)? else {
            continue;
        };
        let id = format!(
            "session:{}",
            path.file_stem()
                .and_then(|name| name.to_str())
                .unwrap_or("unknown")
        );
        entries.push(MemoryIndexEntry {
            id,
            layer: MemoryLayer::L4SessionArchive,
            title: "Session Trace".to_string(),
            keywords: keywords_from_text(&summary),
            path: path.clone(),
            summary,
            updated_at: modified_at(&path),
        });
    }
    Ok(())
}

fn session_summary(path: &Path) -> Result<Option<String>> {
    let file = fs::File::open(path).with_context(|| format!("open {}", path.display()))?;
    let reader = BufReader::new(file);
    let mut goal = None;
    let mut finished = None;
    for line in reader.lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        let value: Value = serde_json::from_str(&line)?;
        let Some(event) = value.get("event") else {
            continue;
        };
        match event.get("type").and_then(Value::as_str) {
            Some("run_started") => {
                goal = event
                    .get("goal")
                    .and_then(Value::as_str)
                    .map(ToString::to_string);
            }
            Some("run_finished") => {
                finished = event
                    .get("summary")
                    .and_then(Value::as_str)
                    .map(ToString::to_string);
            }
            _ => {}
        }
    }
    Ok(match (goal, finished) {
        (Some(goal), Some(summary)) => Some(format!("{goal} -> {summary}")),
        (Some(goal), None) => Some(goal),
        _ => None,
    })
}

fn write_if_missing(path: &Path, body: &str) -> Result<()> {
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    fs::write(path, body).with_context(|| format!("write {}", path.display()))
}

fn modified_at(path: &Path) -> Option<DateTime<Utc>> {
    let modified = path.metadata().ok()?.modified().ok()?;
    Some(DateTime::<Utc>::from(modified))
}

fn heading(body: &str) -> Option<String> {
    content_without_front_matter(body)
        .lines()
        .find_map(|line| line.trim().strip_prefix("# ").map(str::trim))
        .filter(|line| !line.is_empty())
        .map(ToString::to_string)
}

fn first_content_line(body: &str) -> Option<String> {
    content_without_front_matter(body)
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| compact_text(line, 220))
}

fn content_without_front_matter(body: &str) -> &str {
    let Some(rest) = body.strip_prefix("---\n") else {
        return body;
    };
    let Some(end) = rest.find("\n---") else {
        return body;
    };
    let content = &rest[end + "\n---".len()..];
    content.strip_prefix('\n').unwrap_or(content)
}

fn keywords_from_text(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    for term in terms(text) {
        if !out.contains(&term) {
            out.push(term);
        }
        if out.len() >= 16 {
            break;
        }
    }
    out
}

fn terms(text: &str) -> Vec<String> {
    text.split(|ch: char| !ch.is_alphanumeric() && ch != '_' && ch != '-')
        .map(str::trim)
        .filter(|term| term.len() >= 2)
        .map(str::to_lowercase)
        .collect()
}

fn slug(text: &str) -> String {
    let mut out = String::new();
    let mut last_dash = false;
    for ch in text.chars().flat_map(char::to_lowercase) {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    out.trim_matches('-').to_string()
}

fn compact_text(text: &str, limit: usize) -> String {
    let mut text = text.split_whitespace().collect::<Vec<_>>().join(" ");
    if text.len() > limit {
        truncate_utf8(&mut text, limit);
        text.push_str(" ...");
    }
    text
}

fn truncate_utf8(text: &mut String, limit: usize) {
    if text.len() <= limit {
        return;
    }
    let mut end = limit;
    while !text.is_char_boundary(end) {
        end -= 1;
    }
    text.truncate(end);
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn builds_searchable_index_from_memory_and_skills() {
        let root = temp_root();
        let paths = MemoryPaths::new(
            root.join("memory"),
            root.join("skills"),
            root.join("sessions"),
        );
        fs::create_dir_all(root.join("skills/demo")).unwrap();
        fs::write(
            root.join("skills/demo/SKILL.md"),
            "# demo-shell\n\nRun shell checks.",
        )
        .unwrap();

        let index = rebuild_index(&paths).unwrap();
        let hits = search_index(&index, "shell", 5);

        assert!(index.entries.iter().any(|entry| entry.id == "meta-rules"));
        assert!(hits.iter().any(|entry| entry.id == "skill:demo-shell"));
        assert!(paths.index_path().is_file());
    }

    #[test]
    fn fetches_memory_entry_by_id() {
        let root = temp_root();
        let paths = MemoryPaths::new(
            root.join("memory"),
            root.join("skills"),
            root.join("sessions"),
        );
        rebuild_index(&paths).unwrap();

        let doc = fetch_memory(&paths, "meta-rules", 10_000).unwrap();

        assert_eq!(doc.entry.layer, MemoryLayer::L0MetaRules);
        assert!(doc.body.contains("Meta Rules"));
    }

    #[test]
    fn rebuild_writes_pointer_only_l1_insight() {
        let root = temp_root();
        let paths = MemoryPaths::new(
            root.join("memory"),
            root.join("skills"),
            root.join("sessions"),
        );
        fs::create_dir_all(root.join("skills/demo")).unwrap();
        fs::write(
            root.join("skills/demo/SKILL.md"),
            "# demo-shell\n\nRun shell checks.",
        )
        .unwrap();

        let index = rebuild_index(&paths).unwrap();
        let insight = fs::read_to_string(paths.l1_insight_path()).unwrap();

        assert!(insight.contains("# L1 Insight"));
        assert!(insight.contains("demo-shell"));
        assert!(insight.lines().count() <= 30);
        assert_eq!(render_l1_insight(&index, 18), insight);
    }

    #[test]
    fn indexes_skill_content_after_front_matter() {
        let root = temp_root();
        let paths = MemoryPaths::new(
            root.join("memory"),
            root.join("skills"),
            root.join("sessions"),
        );
        fs::create_dir_all(root.join("skills/repoprompt-deep-plan")).unwrap();
        fs::write(
            root.join("skills/repoprompt-deep-plan/SKILL.md"),
            "---\nname: RepoPrompt Deep Plan\ndescription: Plan with RepoPrompt.\n---\n\n# RepoPrompt Deep Plan\n\nUse builder export for planning.\n",
        )
        .unwrap();

        let index = rebuild_index(&paths).unwrap();
        let entry = index
            .entries
            .iter()
            .find(|entry| entry.id == "skill:repoprompt-deep-plan")
            .unwrap();

        assert_eq!(entry.summary, "Use builder export for planning.");
        assert!(!entry.keywords.contains(&"---".to_string()));
    }

    #[test]
    fn durable_memory_guardrails_reject_secrets_and_guesswork() {
        assert!(durable_memory_violations("token: sk-1234567890abcdef").len() == 1);
        assert!(durable_memory_violations("Probably useful later.").len() == 1);
        assert!(durable_memory_violations("Verified by cargo test on 2026-05-22.").is_empty());
    }

    #[test]
    fn compact_text_does_not_split_utf8() {
        let text = compact_text("优化 当前 的 项目 优化 当前 的 项目", 13);

        assert!(text.ends_with(" ..."));
    }

    #[test]
    fn fetch_memory_truncates_utf8_safely() {
        let root = temp_root();
        let paths = MemoryPaths::new(
            root.join("memory"),
            root.join("skills"),
            root.join("sessions"),
        );
        fs::create_dir_all(root.join("memory")).unwrap();
        let memory_path = root.join("memory/chinese.md");
        fs::write(
            &memory_path,
            "# 中文记忆\n\n优化当前的项目优化当前的项目优化当前的项目",
        )
        .unwrap();
        fs::write(
            paths.index_path(),
            serde_json::to_string(&MemoryIndex {
                entries: vec![MemoryIndexEntry {
                    id: "chinese".to_string(),
                    layer: MemoryLayer::L2GlobalFacts,
                    title: "中文记忆".to_string(),
                    keywords: vec!["优化".to_string()],
                    path: memory_path,
                    summary: "中文".to_string(),
                    updated_at: None,
                }],
            })
            .unwrap(),
        )
        .unwrap();

        let doc = fetch_memory(&paths, "chinese", 17).unwrap();
        assert!(doc.body.ends_with("\n...[truncated]..."));
        let _ = fs::remove_dir_all(root);
    }

    fn temp_root() -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("seed-memory-test-{nanos}"))
    }
}
